### ISSUE TITLE
Provide a method for supporting *bug in tests

### ISSUE THREAD

**Issue by CareyJWilliams** [ChoicescriptIDE/cslib#19]
In cslib we want to throw *bug when a user makes an input error and give them a message with detail on what they did wrong. This is impossible to test normally, as it will cause the engine to crash-out and prevent further tests running.

@diegoboston suggested we could override Scene.prototype.bug to instead define an errno/state like variable we can check instead. We can add this to a mygame.js that is only consumed by our Github CI to prevent leaking to production.

**Comment by diegoboston** [comment]
Yes, I can do this.
