### ISSUE TITLE
Implement cslib_string's consist_of

### ISSUE THREAD

**Issue by CareyJWilliams** [ChoicescriptIDE/cslib#3]
The inverse of 'contains', 'consist_of' should return TRUE only when the given string consists entirely of characters in the char string.

```
*temp ws "abbbababababac"
*gosub_scene cslib_string consists_of "abc"
${cslib_ret} == true

*temp ws "abbbaba bababac"
*gosub_scene cslib_string consists_of "abc"
${cslib_ret} == false

*temp ws "     "
*gosub_scene cslib_string is_space ws " "
${cslib_ret} == true
``` 

@danspinola also suggested we could add an `is_(white?)space` alias.

**Comment by danspinola** [comment]
I call shotgun! 🖐🏻

**Comment by danspinola** [comment]
I have two questions:

1.  If either the string or the charset is empty, how should we treat it?
    1.  return true if both are empty, and false otherwise?
    2.  always return false in these cases.
    3.  raise error.
2.  Should the string consist _o_nly of characters in the charset, or should it consist of _e_very character in the charset?  
    For example, `abababababab` consists of _o_nly `abc`, but not of _every_ character in `abc`.

**Comment by CareyJWilliams** [comment]
I'd say an empty charset should be a *bug (considered user error).
Empty string... I vote always return false? It can't consist of anything if it doesn't ... consist of anything? o.O

I was thinking _only_, i.e. if "abc" but your string is "abbbababa", that's valid. I think that's the most useful: for input validation and what-not. What do you think?

**Comment by danspinola** [comment]
I agree that only is more useful. I just wanted to clear that out, anyway.

I agree with the handling of empty params.
