### ISSUE TITLE
Decide on license

### ISSUE THREAD

**Issue by CareyJWilliams** [ChoicescriptIDE/cslib#8]
I'm OK with MIT? What about you guys?
We should also point out that anything people to do still has to adhere to the ChoiceScript license as well: https://www.choiceofgames.com/LICENSE-1.0.txt

**Comment by danspinola** [comment]
I'm good with MIT.

[https://choosealicense.com](https://choosealicense.com)

https://tldrlegal.com/

**Comment by CareyJWilliams** [comment]
That works for me, if it's compatible with the ChoiceScript license.

**Comment by danspinola** [comment]
It should be. We're not granting permission to use ChoiceScript itself, only the library.

**Comment by CareyJWilliams** [comment]
Resolved by https://github.com/ChoicescriptIDE/cslib/commit/a1a32a9d2f7ee047ca013cb4b8e0c4f3b1c59525.
